const wordList = [
    { word: "abacus", hint: "An ancient calculating tool" },
    { word: "balloon", hint: "Fills with air or gas" },
    { word: "cactus", hint: "Desert plant" },
    { word: "daffodil", hint: "Spring flower" },
    { word: "echo", hint: "Repeating sound" },
    { word: "feather", hint: "Light body covering of birds" },
    { word: "galaxy", hint: "Collection of stars" },
    { word: "horizon", hint: "Where earth meets sky" },
    { word: "igloo", hint: "Dome-shaped snow house" },
    { word: "jigsaw", hint: "Piece-fitting puzzle" },
    { word: "kangaroo", hint: "Jumping Australian animal" },
    { word: "lantern", hint: "Portable light source" },
    { word: "magnet", hint: "Attracts certain metals" },
    { word: "nebula", hint: "Cloud in space" },
    { word: "oasis", hint: "Desert water source" },
    { word: "parachute", hint: "Slows air descent" },
    { word: "rainbow", hint: "Colorful sky arc" },
    { word: "tornado", hint: "Violent whirling wind" },
    { word: "umbrella", hint: "Rain protection" },
    { word: "volcano", hint: "Erupting mountain" },
    { word: "waterfall", hint: "Falling water stream" },
    { word: "xylophone", hint: "Percussion instrument" },
    { word: "yacht", hint: "Luxury boat" },
    { word: "zebra", hint: "Striped African animal" },
    { word: "avalanche", hint: "Snow slide" },
    { word: "blossom", hint: "Flowering stage" },
    { word: "caterpillar", hint: "Butterfly larva" },
    { word: "dandelion", hint: "Common yellow flower" },
    { word: "eclipse", hint: "Celestial shadow" },
    { word: "flamingo", hint: "Pink wading bird" },
    { word: "geyser", hint: "Erupting hot spring" },
    { word: "hammock", hint: "Suspended bed" },
    { word: "icicle", hint: "Hanging ice formation" },
    { word: "jellyfish", hint: "Stinging sea creature" },
    { word: "lighthouse", hint: "Coastal warning tower" },
    { word: "meteorite", hint: "Space rock on Earth" },
    { word: "penguin", hint: "Flightless polar bird" },
    { word: "quicksand", hint: "Dangerous ground" },
    { word: "scarecrow", hint: "Crop protector" },
    { word: "unicorn", hint: "Mythical horned horse" },
    { word: "windmill", hint: "Wind-powered structure" },
    { word: "acrobat", hint: "Agile performer" },
    { word: "bamboo", hint: "Fast-growing plant" },
    { word: "dinosaur", hint: "Prehistoric reptile" },
    { word: "firefly", hint: "Glowing insect" },
    { word: "grasshopper", hint: "Jumping insect" },
    { word: "incense", hint: "Aromatic smoke" },
    { word: "kiwi", hint: "Flightless New Zealand bird" },
    { word: "labyrinth", hint: "Complex maze" },
    { word: "monarch", hint: "Royal ruler" },
    { word: "origami", hint: "Paper folding art" },
    { word: "platypus", hint: "Duck-billed mammal" },
    { word: "raccoon", hint: "Masked nocturnal animal" },
    { word: "teepee", hint: "Conical tent" },
    { word: "ukulele", hint: "Small guitar-like instrument" },
    { word: "walrus", hint: "Arctic marine mammal" },
    { word: "zipper", hint: "Teeth-like fastener" },
    { word: "boomerang", hint: "Returning throwing stick" },
    { word: "chameleon", hint: "Color-changing lizard" },
    { word: "evergreen", hint: "Always green tree" },
    { word: "flamenco", hint: "Spanish dance" },
    { word: "gondola", hint: "Venetian boat" },
    { word: "harmonica", hint: "Mouth-blown instrument" },
    { word: "iguana", hint: "Large tropical lizard" },
    { word: "javelin", hint: "Throwing spear" },
    { word: "kimono", hint: "Japanese garment" },
    { word: "lemur", hint: "Madagascar primate" },
    { word: "mosaic", hint: "Tiled picture" },
    { word: "obelisk", hint: "Tall stone monument" },
    { word: "piranha", hint: "Carnivorous fish" },
    { word: "reindeer", hint: "Arctic deer" },
    { word: "scorpion", hint: "Stinging arachnid" },
    { word: "tarantula", hint: "Large hairy spider" },
    { word: "vampire", hint: "Blood-sucking mythical being" },
    { word: "werewolf", hint: "Man-wolf shapeshifter" },
    { word: "yogurt", hint: "Fermented milk product" },
    { word: "zucchini", hint: "Green summer squash" },
    { word: "asteroid", hint: "Small celestial body" },
    { word: "blizzard", hint: "Severe snowstorm" },
    { word: "cricket", hint: "Chirping insect" },
    { word: "dolphin", hint: "Intelligent sea mammal" },
    { word: "eclipse", hint: "Celestial shadow" },
    { word: "falcon", hint: "Bird of prey" },
    { word: "glacier", hint: "Slow-moving ice mass" },
    { word: "octopus", hint: "Eight-armed sea creature" },
    { word: "pyramid", hint: "Ancient Egyptian structure" },
    { word: "squid", hint: "Ten-armed sea creature" },
    { word: "tsunami", hint: "Giant ocean wave" },
    { word: "vampire", hint: "Mythical blood-drinker" },
    { word: "waffle", hint: "Gridded breakfast food" },
    { word: "yacht", hint: "Luxury sailing vessel" },
    { word: "zenith", hint: "Highest point" },
    {
        word: "astronomy",
        hint: "The study of celestial objects and the universe.",
    },
    {
        word: "brouhaha",
        hint: "A noisy and overexcited reaction or response to something.",
    },
    {
        word: "camaraderie",
        hint: "Mutual trust and friendship among people who spend a lot of time together.",
    },
    {
        word: "dichotomy",
        hint: "A division or contrast between two things that are or are represented as being opposed or entirely different.",
    },
    {
        word: "eclectic",
        hint: "Deriving ideas, style, or taste from a broad and diverse range of sources.",
    },
    {
        word: "facetious",
        hint: "Treating serious issues with deliberately inappropriate humor.",
    },
    { word: "gregarious", hint: "Fond of company; sociable." },
    {
        word: "hyperbole",
        hint: "Exaggerated statements or claims not meant to be taken literally.",
    },
    {
        word: "iconoclast",
        hint: "A person who attacks or criticizes cherished beliefs or institutions.",
    },
    {
        word: "juxtapose",
        hint: "Place or deal with close together for contrasting effect.",
    },
    {
        word: "kaleidoscope",
        hint: "A constantly changing pattern or sequence of elements.",
    },
    { word: "laconic", hint: "Using very few words." },
    {
        word: "misanthrope",
        hint: "A person who dislikes humankind and avoids human society.",
    },
    { word: "nefarious", hint: "Wicked or criminal." },
    {
        word: "ostentatious",
        hint: "Characterized by vulgar or pretentious display; designed to impress or attract notice.",
    },
    {
        word: "paradox",
        hint: "A seemingly absurd or self-contradictory statement or proposition that when investigated may prove to be well-founded or true.",
    },
    {
        word: "quixotic",
        hint: "Exceedingly idealistic; unrealistic and impractical.",
    },
    {
        word: "recalcitrant",
        hint: "Having an obstinately uncooperative attitude toward authority or discipline.",
    },
    {
        word: "sagacious",
        hint: "Having or showing keen mental discernment and good judgment; shrewd.",
    },
    {
        word: "tantamount",
        hint: "Equivalent in seriousness to; virtually the same as.",
    },
    { word: "ubiquitous", hint: "Present, appearing, or found everywhere." },
    { word: "verisimilitude", hint: "The appearance of being true or real." },
    {
        word: "whimsical",
        hint: "Playfully quaint or fanciful, especially in an appealing and amusing way.",
    },
    {
        word: "xenophobia",
        hint: "Dislike of or prejudice against people from other countries.",
    },
    {
        word: "yokel",
        hint: "An uneducated and unsophisticated person from the countryside.",
    },
    { word: "zephyr", hint: "A gentle, mild breeze." },
    {
        word: "ambiguous",
        hint: "Open to more than one interpretation; having a double meaning.",
    },
    { word: "benevolent", hint: "Well-meaning and kindly." },
    {
        word: "capricious",
        hint: "Given to sudden and unaccountable changes of mood or behavior.",
    },
    {
        word: "dogmatic",
        hint: "Inclined to lay down principles as incontrovertibly true.",
    },
    { word: "elucidate", hint: "Make (something) clear; explain." },
    { word: "fortuitous", hint: "Happening by a lucky chance; fortunate." },
    {
        word: "harbinger",
        hint: "A person or thing that announces or signals the approach of another.",
    },
    {
        word: "insidious",
        hint: "Proceeding in a gradual, subtle way, but with harmful effects.",
    },
    { word: "jovial", hint: "Cheerful and friendly." },
    {
        word: "luminous",
        hint: "Full of or shedding light; bright or shining, especially in the dark.",
    },
    {
        word: "magnanimous",
        hint: "Generous or forgiving, especially toward a rival or less powerful person.",
    },
    { word: "nocturnal", hint: "Active at night." },
    {
        word: "oblivious",
        hint: "Not aware of or not concerned about what is happening around one.",
    },
    {
        word: "pragmatic",
        hint: "Dealing with things sensibly and realistically in a way that is based on practical rather than theoretical considerations.",
    },
    {
        word: "quintessential",
        hint: "Representing the most perfect or typical example of a quality or class.",
    },
    {
        word: "resilient",
        hint: "Able to withstand or recover quickly from difficult conditions.",
    },
    {
        word: "serendipity",
        hint: "The occurrence and development of events by chance in a happy or beneficial way.",
    },
    {
        word: "tenacious",
        hint: "Tending to keep a firm hold of something; clinging or adhering closely.",
    },
    {
        word: "unfathomable",
        hint: "Incapable of being fully explored or understood.",
    },
    {
        word: "voracious",
        hint: "Wanting or devouring great quantities of food.",
    },
    { word: "wanton", hint: "Deliberate and unprovoked." },
    {
        word: "yearn",
        hint: "Have an intense feeling of longing for something, typically something that one has lost or been separated from.",
    },
    {
        word: "zenith",
        hint: "The time at which something is most powerful or successful.",
    },
    {
        word: "aberration",
        hint: "A departure from what is normal, usual, or expected.",
    },
    { word: "belligerent", hint: "Hostile and aggressive." },
    {
        word: "circumlocution",
        hint: "The use of many words where fewer would do.",
    },
    { word: "dissonance", hint: "Lack of harmony among musical notes." },
    { word: "effervescent", hint: "Vivacious and enthusiastic." },
    { word: "flabbergasted", hint: "Extremely surprised or shocked." },
    {
        word: "grandiloquent",
        hint: "Pompous or extravagant in language, style, or manner.",
    },
    {
        word: "histrionic",
        hint: "Overly theatrical or melodramatic in character or style.",
    },
    { word: "idiosyncratic", hint: "Peculiar or individual." },
    {
        word: "juxtaposition",
        hint: "The fact of two things being seen or placed close together with contrasting effect.",
    },
    { word: "kudos", hint: "Praise and honor received for an achievement." },
    {
        word: "languid",
        hint: "Displaying or having a disinclination for physical exertion or effort; slow and relaxed.",
    },
    { word: "maelstrom", hint: "A powerful whirlpool in the sea or a river." },
    {
        word: "nadir",
        hint: "The lowest point in the fortunes of a person or organization.",
    },
    { word: "obstreperous", hint: "Noisy and difficult to control." },
    { word: "pulchritude", hint: "Beauty." },
    {
        word: "quandary",
        hint: "A state of perplexity or uncertainty over what to do in a difficult situation.",
    },
    {
        word: "reciprocity",
        hint: "The practice of exchanging things with others for mutual benefit.",
    },
    { word: "scintillating", hint: "Sparkling or shining brightly." },
    {
        word: "turbulence",
        hint: "Violent or unsteady movement of air or water, or of some other fluid.",
    },
    {
        word: "ubiquity",
        hint: "The fact of appearing everywhere or of being very common.",
    },
    {
        word: "vacillate",
        hint: "Waver between different opinions or actions; be indecisive.",
    },
    {
        word: "whirlwind",
        hint: "A column of air moving rapidly around and around in a cylindrical or funnel shape.",
    },
    {
        word: "xylophone",
        hint: "A musical instrument played by striking a row of wooden bars of graduated length with one or more small wooden or plastic mallets.",
    },
    {
        word: "yesteryear",
        hint: "Last year or the recent past, especially as nostalgically recalled.",
    },
    { word: "zealous", hint: "Having or showing zeal." },
    {
        word: "apocryphal",
        hint: "Of doubtful authenticity, although widely circulated as being true.",
    },
    { word: "boisterous", hint: "Noisy, energetic, and cheerful; rowdy." },
    { word: "cognizant", hint: "Having knowledge or being aware of." },
    { word: "deleterious", hint: "Causing harm or damage." },
    {
        word: "exacerbate",
        hint: "Make (a problem, bad situation, or negative feeling) worse.",
    },
    { word: "flummox", hint: "Perplex (someone) greatly; bewilder." },
    { word: "gregarious", hint: "Fond of company; sociable." },
    { word: "hapless", hint: "Unfortunate." },
    { word: "impervious", hint: "Not allowing fluid to pass through." },
    {
        word: "juxtaposition",
        hint: "The fact of two things being seen or placed close together with contrasting effect.",
    },
    {
        word: "kaleidoscope",
        hint: "A constantly changing pattern or sequence of elements.",
    },
    { word: "lugubrious", hint: "Looking or sounding sad and dismal." },
    { word: "mendacious", hint: "Not telling the truth; lying." },
    {
        word: "nonchalant",
        hint: "Feeling or appearing casually calm and relaxed; not displaying anxiety, interest, or enthusiasm.",
    },
    { word: "obfuscate", hint: "Render obscure, unclear, or unintelligible." },
    {
        word: "paragon",
        hint: "A person or thing regarded as a perfect example of a particular quality.",
    },
    {
        word: "quagmire",
        hint: "A soft boggy area of land that gives way underfoot.",
    },
    { word: "reverberate", hint: "Be repeated several times as an echo." },
    {
        word: "sophisticated",
        hint: "Having, revealing, or proceeding from a great deal of worldly experience and knowledge of fashion and culture.",
    },
    { word: "tumultuous", hint: "Making a loud, confused noise; uproarious." },
    { word: "unanimous", hint: "Fully in agreement." },
    {
        word: "verbatim",
        hint: "In exactly the same words as were used originally.",
    },
    {
        word: "wistful",
        hint: "Having or showing a feeling of vague or regretful longing.",
    },
]

export default wordList
